name: edupro
description: Aplicación móvil de Edupro
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^5.6.8
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  http: ^1.1.0
  device_info_plus: ^9.0.2
  # JS interop (PromiseJsImpl)
  js: ^0.6.4
  google_sign_in: ^7.2.0

  # Estado y preferencias
  provider: ^6.0.5

  # Gráficas, enlaces y formatos
  fl_chart: ^1.0.0
  url_launcher: ^6.2.4

  # Firebase (core + auth + mensajería)
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4 
  firebase_auth_web: ^5.14.3
  firebase_messaging: ^15.2.6
  firebase_messaging_web: ^3.10.6
  table_calendar: ^3.0.9


  # Selección de archivos para adjuntos
  file_picker: ^10.1.9
  cloud_functions: ^5.6.2
  crypto: ^3.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/LogoAdmin.png
    - assets/LogoAlumnos.png
    - assets/LogoDocentes.png
